authors = ["Daniel H. Morgan <dhmorgan@protonmail.com>"]
name = "ScalarTime"
uuid = "541787ee-c1a9-11e8-15fe-73598bddbdd6"
version = "0.1.0"

[deps]

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
